services:
  api:
    build: ./api
    container_name: api
    ports:
      - '3000:3000'
    depends_on:
      - db
    env_file:
      - ./api/.env

  frontend:
    build: ./frontend
    container_name: frontend
    ports:
      - '5173:5173'
    depends_on:
      - api
    env_file:
      - ./frontend/.env

  db:
    image: postgres:17
    container_name: postgres
    environment:
      - POSTGRES_DB=ratings_app_db
      - POSTGRES_USER=roxiler
      - POSTGRES_PASSWORD=roxiler
    ports:
      - '5432:5432'
    volumes:
      - ./db/initiate_db.sql:/docker-entrypoint-initdb.d/init.sql:ro
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped
    
volumes:
  postgres_data:
